import 'package:elan/domain/pricing_config/pricing_config.dart';
import 'package:elan/presentation/bloc/pricing_config_bloc/pricing_config_bloc.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

/// Label helpers over [PricingConfig].
///
/// Renamed from `PricingConfig` when the two parallel implementations of this
/// feature were merged: that name now belongs to the freezed model in
/// `domain/pricing_config/`, which already guarantees non-null values through
/// `@Default`s. What survives here is the part that model does not do — turning
/// numbers into pluralised copy ("6 hours", "7 days").
class PricingConfigView {
  const PricingConfigView(this._config, {this.isLoaded = true});

  final PricingConfig? _config;

  /// False while [_config] is compiled-in defaults or a cached copy rather than
  /// a fresh server response — the bloc's `isFallback`, inverted. Use it to
  /// hide optional copy (e.g. payout-delay hints) rather than to gate
  /// rendering.
  final bool isLoaded;

  // `.toInt()` throughout: the freezed model types these as `num` so a server
  // sending `6.0` still parses, but the label helpers below want whole units.

  // ---- Rates (cents) ----

  /// Instructor hourly rate. Fallback for `EarningsSummary.hourlyRate`, which
  /// is null until the dashboard summary resolves.
  num get instructorRate => _config?.instructorRate ?? 6000;

  num get baseRate => _config?.baseRate ?? 200;

  num get normalRate => _config?.normalRate ?? 100;

  num get baseDistance => _config?.baseDistance ?? 50;

  num get averageDistancePerHour => _config?.averageDistancePerHour ?? 100;

  /// Rough travel-time estimate for [distanceKm] at the configured average
  /// speed.
  ///
  /// Only a fallback for when Google Directions has no route — it is not a
  /// substitute for a real ETA. Returns `--` for a zero/unknown distance.
  String estimateTravelTime(num? distanceKm) {
    final km = (distanceKm ?? 0).toDouble();
    final speed = averageDistancePerHour.toDouble();
    if (km <= 0 || speed <= 0) return '--';

    final hours = km / speed;
    return hours < 1
        ? '~${(hours * 60).round()} min'
        : '~${hours.toStringAsFixed(1)} hr';
  }

  // ---- Referrals ----

  /// Bonus for a code generated by an instructor (cents).
  num get instructorReferralPrice => _config?.instructorReferralPrice ?? 10000;

  /// Bonus for an admin-issued promo code (cents).
  num get adminReferralPrice => _config?.adminReferralPrice ?? 12000;

  /// Rides the referee must complete before the bonus unlocks.
  int get referralMinRides => (_config?.referralMinRides ?? 5).toInt();

  /// Bonus for a given `referral_type` from the referral-code endpoints.
  /// Falls back to the instructor price for unknown types.
  num referralPriceFor(String? referralType) {
    return referralType?.toLowerCase() == 'admin'
        ? adminReferralPrice
        : instructorReferralPrice;
  }

  // ---- Ride timing ----

  /// How long before the test time a ride may be started.
  int get rideStartWindowHours => (_config?.rideStartWindowHours ?? 6).toInt();

  /// Deadline before the test time for requesting a transfer.
  int get rideTransferCutoffHours =>
      (_config?.rideTransferCutoffHours ?? 6).toInt();

  /// `6 hours` / `1 hour` — config values are operator-editable, so never
  /// hardcode the plural.
  String get rideStartWindowLabel => _hours(rideStartWindowHours);

  String get rideTransferCutoffLabel => _hours(rideTransferCutoffHours);

  String get payoutDelayLabel {
    final days = instructorPayoutDelayDays;
    return '$days day${days == 1 ? '' : 's'}';
  }

  static String _hours(int value) => '$value hour${value == 1 ? '' : 's'}';

  int get bookingMinLeadDays => (_config?.bookingMinLeadDays ?? 1).toInt();

  // ---- Payouts ----

  int get instructorPayoutDelayDays =>
      (_config?.instructorPayoutDelayDays ?? 7).toInt();

  // ---- Refunds (student-facing; exposed for completeness) ----

  int get refundFullHours => (_config?.refundFullHours ?? 48).toInt();

  int get refundPartialHours => (_config?.refundPartialHours ?? 24).toInt();

  num get refundPartialPercentage => _config?.refundPartialPercentage ?? 50;

  num get failureCouponPercentage => _config?.failureCouponPercentage ?? 10;

  int get failureCouponValidityMonths =>
      (_config?.failureCouponValidityMonths ?? 6).toInt();
}

extension PricingConfigContextX on BuildContext {
  /// Rebuilds the caller when the config arrives.
  PricingConfigView get pricing {
    final state = watch<PricingConfigBloc>().state;
    return PricingConfigView(state.config, isLoaded: !state.isFallback);
  }

  /// Non-reactive read, for callbacks and `initState`.
  PricingConfigView get pricingOnce {
    final state = read<PricingConfigBloc>().state;
    return PricingConfigView(state.config, isLoaded: !state.isFallback);
  }
}
